scrape_configs:
  - job_name: glances
    static_configs:
      - targets: ["node1.lan:9091"]
        labels:
          node: "node1"
      - targets: ["node2.lan:9091"]
        labels:
          node: "node2"
      - targets: ["node3.lan:9091"]
        labels:
          node: "node3"
      - targets: ["mindgate.lan:9091"]
        labels:
          node: "mindgate"
      - targets: ["enigma.lan:9091","enigma.lan:9094"]
        labels:
          node: "enigma"
  - job_name: otel-collector
    static_configs:
      - targets: ["node1.lan:9464"]
        labels:
          node: "node1"
